### ISSUE TITLE
[1.12.2/Question] Still blink Needs [Tyros].

### ISSUE THREAD

**Issue by Tronif** [mcenderdragon/Futurepack-API#469] opened 2018-07-17 05:00 UTC
FuturePack Version: 26.3.210

I have already reached The Tyros, but the "Needs [Tyros]" icon still blink and the research will not be completed. Is there not enough research about The Tyros? Others that are likely to be researched remain only about "Laser Bow", and I do not know how to research this.

**Comment by Maxwell-lt** [comment] 2018-08-27 04:20
I also have the same issue, the research is not unlocked despite receiving the advancement. Looking at the research.json file, there doesn't seem to be any reason why it's not detecting the advancement.

Because you can't get the research unlocked, it's impossible to research things like the Bioterium Sword and NoN components. Based on how there's no description text yet, NoN might not be implemented yet, but the Bioterium Sword has a complete description.

I'm also using 26.3.210.

EDIT: What you can do to mitigate the issue is running the command `/fp research <player name> unlock tyros`, which will let you get the Bioterium Sword, NoN Core and NoN RAM.

**Comment by mcenderdragon** [comment] 2018-10-07 12:24
Should be fixed in 417

**Closed as completed by mcenderdragon** 2018-10-07 12:24 UTC
