### ISSUE TITLE
[1.18.2 Crash Dedicated Server] Ticking Block

### ISSUE THREAD

**Issue by itsdinkd** [mcenderdragon/Futurepack-API#899] opened 2022-06-08 10:57 UTC
https://gist.github.com/itsdinkd/99ab506bd28e401e8437f96f57151ebc

futurepack; 033.0.7327
mc; 1.18.2
forge loader; 14.1.20
dedicated server

**Comment by mcenderdragon** [comment] 2022-06-08 14:50
disable RF support in the config for now

**Comment by mcenderdragon** [comment] 2022-06-08 14:50
duplicate of https://github.com/mcenderdragon/Futurepack-API/issues/898

**Closed as completed by mcenderdragon** 2022-06-08 14:50 UTC
Labels: Bug, invalid/duplicated, Solved in Dev, 1.18.x

**Comment by itsdinkd** [comment] 2022-06-12 19:12
is this fixed in the june 8th update?

**Comment by mcenderdragon** [comment] 2022-06-12 19:16
in [Futurepack-1.18.2-33.0.7358.jar](https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3823001) this should be fixed (hence the solved in dev tag and then closign of this issue)

**Comment by itsdinkd** [comment] 2022-06-14 01:11
> in [Futurepack-1.18.2-33.0.7358.jar](https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3823001) this should be fixed (hence the solved in dev tag and then closign of this issue)

Yep. saw the "Solved in Dev" however, In dev does not mean prod aka the latest CF release :)

Thank you for fixing.

**Comment by mcenderdragon** [comment] 2022-06-14 11:34
> > in [Futurepack-1.18.2-33.0.7358.jar](https://www.curseforge.com/minecraft/mc-mods/futurepack/files/3823001) this should be fixed (hence the solved in dev tag and then closign of this issue)
> 
> Yep. saw the "Solved in Dev" however, In dev does not mean prod aka the latest CF release :)
> 
> Thank you for fixing.

understandable. in https://github.com/mcenderdragon/Futurepack-API/issues/898 you can see 6 days ago i marked it as fixed in dev and 8 days ago i closed it. When I release something on CF i usually close all issues marked as solved in dev
