### ISSUE TITLE
[1.16.4] Fluid pump bug.

### ISSUE THREAD

**Issue by AjzaklijaStomaklija** [mcenderdragon/Futurepack-API#721] opened 2020-12-28 08:17 UTC
When the fluid pump is working it makes all entitys invisible.I tried to exit the game and load it again but nothing.Then i tried to break the pump and then reopen the game and then it fixes it.If you just place the pump in the world its fine,but when you give it neon energy and connect it to water cooler then the bug happens.

**Comment by qrss** [comment] 2020-12-28 12:36
I think this is a Duplicate of #695 

It is supposedly fixed in the Dev branch.

You can try this version and see if the problem persists:
[Futurepack-1.16.4-21.0.2](https://www.mediafire.com/file/fzoix8o0kejl9bf/Futurepack-1.16.4-21.0.2.jar/file)

**Closed as completed** 2020-12-30 16:46 UTC
Labels: invalid/duplicated, Solved in Dev, 1.16.x

**Comment by AjzaklijaStomaklija** [comment] 2020-12-31 17:07
Problem fixed.Good job!
