### ISSUE TITLE
[1.12.2] Shader of paralyzed effect locking up game (v.26.3.417)

### ISSUE THREAD

**Issue by caligator** [mcenderdragon/Futurepack-API#504] opened 2018-10-16 17:26 UTC
when friends were playtesting my pack, they found that falling into Neon Liquid placed in-world causes the game to lock up for them. in testing to recreate, I found that the game does indeed lock up if you touch the liquid. the system returns a recursive error in the log stating; 

**> 12:08:51 | net.minecraft.client.shader.ShaderManager | Could not find uniform named InSize in the specified shader program. -- | -- | --**

you can not move but you can access the menu and the text input for the game. The bug occurs regardless if a player is in creative or survival.
the only way to get unstuck is using /kill on a player. Now, I'm using a fairly beefy pack but its got no real overlap (that I can find) with Futurepack's fluid registry. is there any potential cause/solution to this issue, or has anyone had similar? everything else in FP seems to work fine save for this interaction

heres my forced crash for any further info that might help
https://hastebin.com/uyeqohanip.rb

**Comment by mcenderdragon** [comment] 2018-10-16 19:11
This has not happend to me every before, it seems like this is caused by another mod. Have you OptiFine installed ? If yes remove that and try agian, if not then its one of the core mods and you have to remove them. I can hardly do anything about this as it is happening inside minecrafts shader system.

**Comment by mcenderdragon** [comment] 2018-10-16 19:12
The coremods:
FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  AstralCore (astralsorcery-1.12.2-1.9.4.jar)
  HCASM (HammerCore-1.12.2-2.0.2.3.jar)
  Plugin (NotEnoughIDs-1.5.4.3.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.10-core.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  FMLPlugin (elulib-0.1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-77-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b161.jar)
  MixinLoaderForge (Valkyrien Warfare 0.9_prerelease_5 [Optimization Update].jar)
  EECore (ExpandedEquivalence-1.12.2-11b.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.12-core.jar)

I know from TheBetweenlands they do somethign with shaders, so try to remove them first.

**Comment by caligator** [comment] 2018-10-17 13:17
will do, will post back when I get time to try hammering more out. 👍

**Comment by SkyProgs** [comment] 2021-05-25 16:10
Unfortunately, we can no longer support the 1.12.2 so I'm closing this issue.

**Closed as completed by SkyProgs** 2021-05-25 16:10 UTC
Labels: Bug, Investigation-needed, Rendering/Client
