### ISSUE TITLE
Scanner Block is not displaying all aspects

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#456] opened 2018-06-05 15:33 UTC
![](https://media.discordapp.net/attachments/453579949060915201/453581365884223489/unknown.png?width=900&height=676)

THis results in a complet reserch stop. The button is not pushable.

This happnes on towncraft. @Prospercraft, if you have time, please send me the server logs.

**Comment by ProsperCraft** [comment] 2018-06-08 22:49
[2018-06-08-2.log.gz](https://github.com/mcenderdragon/Futurepack-API/files/2086389/2018-06-08-2.log.gz)
[2018-06-08-3.log.gz](https://github.com/mcenderdragon/Futurepack-API/files/2086390/2018-06-08-3.log.gz)
[2018-06-08-1.log.gz](https://github.com/mcenderdragon/Futurepack-API/files/2086391/2018-06-08-1.log.gz)
Here are some logs, hope it helps.

**Comment by mcenderdragon** [comment] 2018-06-09 21:36
It seems currently more like a client side render bug then a server bug.

**Comment by mcenderdragon** [comment] 2018-06-19 15:58
![the Bug](https://media-minecraftforum.cursecdn.com/attachments/281/986/636649545260238400.png)

Src :https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2644868-futurepack-mod-discover-new-dimensions?comment=448

**Comment by mcenderdragon** [comment] 2018-06-20 17:42
@ProsperCraft I have indentified the cause: some other mod is disbaling  the 9th button of this gui and thats this apsect button. The only thing I can do is to enable alll button each tick. It would be nice if you could check all gui modifiing mods if they are causing this issue. (best starting with coremods)

**Comment by mcenderdragon** [comment] 2018-06-20 19:26
[26.3.266](https://redsnake-games.de/Downloads/fp/fp.php?t=7mUEnFlrxRFZ2N9.0UcTiw--) This should fix the problem, but please check.

**Comment by Darianna77** [comment] 2018-06-21 07:05
I have testet it :) It works for me....big thx for the fast checking, reaction on the Forum and fot the fast fix! :)

**Comment by mcenderdragon** [comment] 2018-06-21 13:30
Ok so its indeed the visibility field. I wonder which mod is deactivating the button...

**Comment by ProsperCraft** [comment] 2018-06-21 14:39
I suspect toast control or no more recipe book mods

**Comment by mcenderdragon** [comment] 2018-06-21 15:43
Can you test those two ? And then create an issue to fix the bug.

**Comment by Darianna77** [comment] 2018-06-22 09:12
Without Toastcontrol it works..so it seems to be this mod

**Comment by mcenderdragon** [comment] 2018-06-22 19:24
@Darianna77  With the old version or with the newer one ?

**Comment by Darianna77** [comment] 2018-06-22 20:50
Oh i have wrote in german..hups...
With the normal one...not your fixed one

**Comment by mcenderdragon** [comment] 2018-06-22 21:25
I have created an issue at their issue tracker, but I am not sure if its only toastcontrol which is causing this.

**Comment by Darianna77** [comment] 2018-06-22 21:30
I have only can make a short test....put the normal futurepack back in...disable toastcontrol and load my game....ant button was back...all seems fine

**Comment by Shadows-of-Fire** [comment] 2018-06-22 21:54
toast control has no listeners to gui events, nor does it touch the isVisible field of buttons anywhere.

**Comment by Shadows-of-Fire** [comment] 2018-06-22 22:01
@ProsperCraft is this mod present? https://minecraft.curseforge.com/projects/no-recipe-book

**Comment by Shadows-of-Fire** [comment] 2018-06-22 22:03
Or a similar mod, it may not be this one explicitly, but I remember asie mentioning one of the mods that does this doesn't check properly.

**Comment by Darianna77** [comment] 2018-06-22 22:11
But i have only disable Toastcontrol and the Button was back and working

**Comment by Shadows-of-Fire** [comment] 2018-06-22 22:48
Toast control has no code to perform that action.  It cannot do that.

**Comment by ProsperCraft** [comment] 2018-06-22 22:50
@Shadows-of-Fire Yes, as I stated previously.

**Comment by Shadows-of-Fire** [comment] 2018-06-22 23:12
Can confirm it is neither FastWorkbench or Toast Control: ![](https://i.imgur.com/DRVwmVK.png)

**Comment by Shadows-of-Fire** [comment] 2018-06-22 23:13
Which means its probably whatever mod that is trying to remove the recipe book button badly, however FastWorkbench removes it properly, so any other mod claiming to do that can safely be removed.

**Comment by mcenderdragon** [comment] 2018-06-23 01:11
thanks @Shadows-of-Fire for helping :)

**Comment by mcenderdragon** [comment] 2018-06-23 12:10
https://minecraft.curseforge.com/projects/no-recipe-book/issues/2

**Comment by mcenderdragon** [comment] 2018-06-23 12:17
with only Futurepack and no-recipe-book this does not occur. Also by adding placebo & toastcontrol and cant reproduce this.

**Comment by SeneschalLuwin** [comment] 2018-06-23 14:15
Solution: Update NoRecipeBook to the latest release.

**Comment by SeneschalLuwin** [comment] 2018-06-23 14:19
Caused by version 1.2.0 of no-recipe-book. Update to latest release.

**Comment by ProsperCraft** [comment] 2018-06-23 15:31
This has indeed been fixed with the no-recipe-book update.

**Closed as completed** 2018-08-27 12:43 UTC
Labels: Bug, Critical, Solved in Dev, Other Mod's fault/ Mod interaction
