### ISSUE TITLE
1.12 too many bedrock rifts ?

### ISSUE THREAD

**Issue by Zygus42** [mcenderdragon/Futurepack-API#454] opened 2018-05-09 06:48 UTC
Futurepack-1.12.2-26.3.210
forge-1.12.2-14.23.3.2673-installer-win

As I have no idea what they do, not having tried the latest versions of your mod, but there seem to be quite a lot of the bedrock rifts in the game.  Is this the kind of quantity you're aiming for ?

With quantity in the config set to 1, this is how many you get in the nether:
![2018-05-09_14 41 31](https://user-images.githubusercontent.com/20757445/39799579-4ff8e5e8-5397-11e8-896f-51f3de7dba46.png)

And in the overworld (a little harder to see, but I'm looking at 3 in this picture):
![2018-05-09_14 46 33](https://user-images.githubusercontent.com/20757445/39799762-fea439e4-5397-11e8-9068-5ed7b7d14528.png)

**Comment by mcenderdragon** [comment] 2018-10-09 09:30
@Wugand is this intended.

**Comment by Wugand** [comment] 2018-10-09 10:38
The generation in nether is wrong (way to high, they should be plane in Bedrock).
I think the count was fixed in an later version (1 means 50% chance per chunk).
Is it a problem to have many of them?

**Comment by Wugand** [comment] 2018-12-24 22:32
as can be seen in net.minecraft.world.biome.BiomeHellDecorator the Nether normally don't call any Ore Generation. So the expected behavior is no Bedrock Rifts at all. 
So an other mod is fireing the orgen events for Nether.

**Closed as completed** 2019-02-06 14:00 UTC
Labels: Other Mod's fault/ Mod interaction
