### ISSUE TITLE
[1.12.2] Server crash -NullPointerException: Exception in server tick loop 	at futurepack.common.dim.scanning.FPChunkScanner.lambda$onWorldUnload$0

### ISSUE THREAD

**Issue by ProsperCraft** [mcenderdragon/Futurepack-API#614] opened 2020-01-04 18:53 UTC
https://gist.github.com/ProsperCraft/6c7a66fa46980bdd95743ca32aad88bf

On server start, it crashed and gave this crash log-

Futurepack-1.12.2-26.4.88
Server binary - https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/

**Comment by mcenderdragon** [comment] 2020-01-04 19:31
Duplicate of https://github.com/mcenderdragon/Futurepack-API/issues/554

**Closed as completed by mcenderdragon** 2020-01-04 19:31 UTC
Labels: Bug, invalid/duplicated, 1.12.x
