### ISSUE TITLE
TechTree not shown

### ISSUE THREAD

**Issue by Yirok42** [mcenderdragon/Futurepack-API#784] opened 2021-04-06 00:54 UTC
Futurepack-1.16.4-31.1.8176 on MC 1.16.4

**To Reproduce**
1. Go to Scanner and click the Tech Tree button by the Biology aspect,
OR, use an E-Scanner and click on the Tech Tree button
OR, I have not tried a TechTern as I am not near a dungeon with passable hallways
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/65392871/113643151-3a4e8180-9647-11eb-802b-e2b90cdb0bd9.png)

**Additional context**
I was in my single player world yesterday and all was fine.
I tried '/reload' but that seemed to have no effect.
I tried F3+T but that also seemed to have no effect.

**Logs**
Perhaps this is significant:
[05Apr2021 19:35:07.916] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index: 7591, Size: 305
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at futurepack.common.research.ResearchManager.getById(ResearchManager.java:45) ~[?:1.16.4-31.1.8176]
	at futurepack.client.research.LocalPlayerResearchHelper.setupResearching(LocalPlayerResearchHelper.java:65) ~[?:1.16.4-31.1.8176]
	at futurepack.common.sync.MessageResearchResponse.consume(MessageResearchResponse.java:77) ~[?:1.16.4-31.1.8176]
	at futurepack.common.sync.FPPacketHandler$$Lambda$5307/9270560.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$7731/1856265691.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2886/462911221.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2888/244190700.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]

**Comment by Yirok42** [comment] 2021-04-06 03:00
Well I restarted the game or that I wandered away and wandered back, and now I can use the TechTree and also when I make something it shows up in the 'take it box' which i was not doing when the TechTree was broken.

**Comment by mcenderdragon** [comment] 2021-04-23 06:30
This is a LAN world right? I know FOrge had at somepoint major Problems with lan world completly breaking in 1.16.5

**Comment by Yirok42** [comment] 2021-04-28 01:02
yes, it is a LAN world. I sometimes have a server but I try out new versions as LAN.
I was using 1.16.4. Today I switched to 1.16.5 with Forge 36.1 for the impassable dungeon issue.

I do not know if I had the techtree problem much after reporting that but I think I may also have been almost done with looking up things.

**Comment by Yirok42** [comment] 2021-05-20 02:39
In a new LAN world, the order of events was complete researching "super cable" then start researching "ultimate chipset" and I opened a TechTable where I had already placed recipe for Super Cable, when I tried to take the as-built items, GAME CRASH. When I restarted, I took one item off the table, and when I replaced it, the item was no longer buildable. I had a few more crashes, and finally decided to look in the FP_Research json file. I assumed log.supercable would not be present, but it was! I cannot get a recipe for the super cable (probably because I already have that knowledge) but I also cannot craft super cable. I only have the 8 super cable that I got when completing the research.

I put all that here, because at the same time I see the techtree is not showing, and I expect there is a exception somewhere. What logs would you like?

**Comment by mcenderdragon** [comment] 2021-05-20 06:06
can you include teh crash report.

**Comment by Maexel12** [comment] 2021-05-30 21:56
Hello, wanted to add something onto this issue.
We (playing on a LAN World) have the same problem but with only 1 of your player.

That means that i (the host) have no problem with the Techtree and can read every single post but my friend (from him are the attached logs) can't. He has the same overlay as the OP.

This issue happent the moment somewhere between the "researching for retium sword" and "crafting a retium sword" and lasts till... now.

Should i make an own issue or can i help in some other way (never reported something on github)?

[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6566963/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6566964/latest.log)

**Comment by mcenderdragon** [comment] 2021-05-31 07:18
the researches between server & client seems out of sync. I know at some point forge had problems with lan worlds. can you tey woth a dedicated server if the problems are still present ?

**Comment by Maexel12** [comment] 2021-05-31 08:39
After setting up a dedicated server (and copying all the files) it's still the same.

He (the one with the both logs) can't see the techtree, but i still can.
Just to clarify we are playing on an self configured Valhelsia 3 Modpack, and the futurepack version is Futurepack-1.16.4-31.1.8226

**Comment by mcenderdragon** [comment] 2021-05-31 09:44
does this also happen without optifine?

**Comment by Maexel12** [comment] 2021-05-31 10:02
Yes, even after removing optifine he still doesn't see anything in the techtree (but i can)

Current logs from him attached
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6569480/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6569481/latest.log)

**Comment by mcenderdragon** [comment] 2021-05-31 10:16
I think I found a cause for this.

**Comment by mcenderdragon** [comment] 2021-05-31 11:05
can you try this if its fixed: https://www.mediafire.com/file/hdmgqiqggq5l4gj/Futurepack-1.16.4-31.2.6826.jar/file ?

**Comment by Maexel12** [comment] 2021-05-31 11:56
I understood it right to erase the ".zip" part of the file ?

if so, no it didnt. the issue still occoures with him. I had a crash, but i doubt that it has something to do with futurepack.

His (cant see Techtree - logs)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6570050/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6570052/latest.log)

Mine (can see techtree - but crashed after joining world)
[crash-2021-05-31_13.48.19-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/6570059/crash-2021-05-31_13.48.19-server.txt)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6570060/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6570061/latest.log)

Server
[crash-2021-05-31_13.31.40-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/6570062/crash-2021-05-31_13.31.40-server.txt)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6570064/FP-Latest.log)
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/6570065/latest.log)
[debug.log](https://github.com/mcenderdragon/Futurepack-API/files/6570068/debug.log)

**Comment by mcenderdragon** [comment] 2021-05-31 12:21
@Maexel12 what zip part? there is no "zip" in the file name. Also according to the log it is working without issues. So he can still niot see something ?

**Comment by Maexel12** [comment] 2021-05-31 12:27
I figured out the zip part came from mediafire - my bad ;)

He still can not see the icons from the techtree (like in the upper pictures)

**Comment by mcenderdragon** [comment] 2021-05-31 12:32
hmm then another issue is fixed. I dont know what is causing this...

**Comment by Maexel12** [comment] 2021-05-31 12:40
What can i provide you with or are there any options available to record the issue better?

**Comment by mcenderdragon** [comment] 2021-05-31 13:23
is it possible for you to switch computers? So he is hosting and you are joining ? I want to know if its jsut a hardware issue. Also try to update java.

**Comment by Maexel12** [comment] 2021-05-31 14:03
We will do, i try it out the next days.

**Comment by Maexel12** [comment] 2021-05-31 14:41
update - it works. We both repaired forge and restarted our pcs. It works now 👍

**Comment by mcenderdragon** [comment] 2021-06-09 11:23
Duplicate of #798

**Comment by mcenderdragon** [comment] 2021-06-09 17:17
Maybe also #801 , but both are now fixed

**Closed as completed by mcenderdragon** 2021-06-09 17:17 UTC
Labels: Bug, 1.16.x
