### ISSUE TITLE
Pipe Research Not working

### ISSUE THREAD

**Issue by litjohn50** [mcenderdragon/Futurepack-API#360] opened 2018-01-31 17:11 UTC
For the Grenade Launcher Research it will ask for 4 neon pipes, but when I put them into the researcher it gives a red box.

Same for Support Pipe Research asking for 4 normal pipes. Same issue
https://cdn.discordapp.com/attachments/405010228074119168/408306089814261761/unknown.png
https://cdn.discordapp.com/attachments/405010228074119168/408306174656643072/unknown.png

Redstone Pipe also missing item name.

http://prntscr.com/i89bu2

**Comment by mcenderdragon** [comment] 2018-01-31 17:13
Wich version are you using ? (Futurepack version)

**Comment by mcenderdragon** [comment] 2018-01-31 17:38
this was most likely already fixed in 26.3.76

**Comment by litjohn50** [comment] 2018-01-31 17:38
v.26.3.76

**Comment by mcenderdragon** [comment] 2018-01-31 17:42
how does it look like when you take the item out of the slot ?

**Comment by ProsperCraft** [comment] 2018-01-31 17:45
The server is running -  forge-1.12.2-14.23.1.2607-universal.jar  just for the record.

**Comment by litjohn50** [comment] 2018-01-31 17:46
says that it needs it http://prntscr.com/i89w3b

**Comment by mcenderdragon** [comment] 2018-02-01 08:23
Can you provide the full log ?

**Comment by litjohn50** [comment] 2018-02-03 05:47
There is no crash log. Which log are you talking about how would I be able to get it?

Also this research isn't working either http://prntscr.com/i9gpln
http://prntscr.com/i9gpv8

**Comment by ronsardis** [comment] 2018-02-03 11:42
Having similar issues with the research for 'neon pipe' and 'research module - energy'

https://youtu.be/t3ve9CI7dPY

**Comment by mcenderdragon** [comment] 2018-02-03 14:10
in the logs folder in the latest.log, fml-client-latest.log and the FP-latest.log, I need all three. Also you can try to press F3 + C for more then 10seconds to make a crash report. (they have important information about the world wich dont accour in the logs)

**Comment by litjohn50** [comment] 2018-02-03 15:50
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1691870/latest.log)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/1691871/FP-Latest.log)
[crash-2018-02-03_09.46.37-client.txt](https://github.com/mcenderdragon/Futurepack-API/files/1691874/crash-2018-02-03_09.46.37-client.txt)

I don't have an fml-cilent-latest.log file in my log folder

**Comment by mcenderdragon** [comment] 2018-02-03 16:56
I can not reproduce this weirdness :/. With only [this version (26.3.78)](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.78) does it work ? If yes, does it stop working with all the oher mods ?

**Comment by ronsardis** [comment] 2018-02-03 17:58
problem does not seem to be present in our pack when played in SP, doing further testing.

**Comment by litjohn50** [comment] 2018-02-03 18:34
So far the new version you gave me shows a fix. In single player.

**Comment by mcenderdragon** [comment] 2018-02-03 18:54
Ok at least some  progress  :)

**Comment by mcenderdragon** [comment] 2018-02-07 17:41
I posted another version the the other issue this should also fix this in multiplayer.

**Comment by litjohn50** [comment] 2018-02-08 21:08
Can you push it too curse? We can't test it on multiplayer otherwise.

**Comment by mcenderdragon** [comment] 2018-02-08 22:02
well not realy because of the recent energy system changes, they need further testing before they get realesed. CUrrently they igore the logistic system

**Comment by litjohn50** [comment] 2018-02-08 22:04
Ok then the testing is on hold until that is tested.

**Comment by mcenderdragon** [comment] 2018-02-09 15:52
I posted another version in the other thread, it should work now.

**Comment by mcenderdragon** [comment] 2018-02-10 16:37
posted a final fix, everxthing should work by now.

**Closed as completed** 2018-02-19 17:09 UTC
Labels: Bug, Critical, Solved in Dev
