### ISSUE TITLE
Update to 1.11.2

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#105] opened 2017-01-03 17:06 UTC
Known Bugs:
- [x] Merge changes from 1.10.2
- [x] Crystals produce Firefly Particles
- [x] Crash on Shift-Click at:  ok, every Inventory !
- [x] Charging an empty Battery and empty Flash Memories gives Konstruktionkopierer
- [x] Optibench duplicates Items when taking in/out if an recipe is active (should be fixed, please test - currently not testable)
- [x] Optibench use recipe even if it is taken out
- [x] Crash in optibench: http://pastebin.com/FZsQeBb2   This also destroys the nbt-Tag
- [x] Logistic Editor don't show overlays. 
- [x] Crash/Freeze at opening a Modification GUI: http://pastebin.com/2BwnFwR6  and  http://pastebin.com/VikgLt1h
- [x] Inustrial funace don't accept lava buckets
- [x] Block Breaker destroys Items and don't push/drop
- [x] Pipes creash: http://pastebin.com/xZUfJz8G
- [x] PartPress deletes Fuel Itemstack
- [x] Partpress crash: http://pastebin.com/Xuk3MjpL
- [x] Generator deletes Fuel Itemstack
- [x] Researcher don't Render Items-Hologramms (should be fixed, please test)
- [x] Damage Bars (Laser Rifle, Granade Launcher) looks strange
- [x] Laser Rifle dont render the shot
- [x] Industrial Furnace don't empty lava buckets (not fixed)
- [x] Crash on filling optibench with pipe  (should be fixed, please test - currently not testable)
- [x] Transport Chip don't work  (only fixed in 1.10.2)
- [x] Optibench: TileEnitity is destroyed on world save/load if a recipe is inside. (it get recraeted, like an creative Tab machine; also Chip tuning is lost) -- more tests with optibench impossible
- [x] Crash on placing FuturePack sapling: http://pastebin.com/2kqs8vxX
- [x] Colored Grid Blocks are not uncolorable by airbrush
- [x] Water cooler don't empty water buckets
- [x] Change Paraglider Standart Key (F is not possible)
- [x] No Research discription texts are found, example:  FileNotFoundException: "fp:lang/en_us/techtable.json"; maybe because lowercase "en_US"->"en_us"?
- [x] Falling tree does not render due the FastTESR tests
- [x] Optibench crash (maybe shift-click): http://pastebin.com/Hj3qmtj5
- [x] IndustrialFurnace accept and smelt every Item and smelt to nothing
- [x] NeonIndustrialFurnace accept and smelt every Item and smelt to nothing
- [x] Watercooler crash with hoppers: http://pastebin.com/KXmtDNsM (putting in more buckets then needed, and extracting)
- [x] Menelaus and Tyros always have LightLevel 0
- [x] Monocart Station GUI has multiple bugs
- [x] Slime granade and Feeding granade have no visible projectile
- [x] Entityegger and Entityegger-Granade don't spawn entity, error: "Skipping Entity with id ...". Even if oreginal is dead
- [x] PartPress don't use the second production line (right one)
- [x] PartPress Slots has no rules (output slot not locked, etc.)
- [x] PartPress Shift-Click is not useable to put material in. 
- [x] Finish new Battery/Flash-Capacity system: 
          -- remove empty batteries, flash drives
          -- change recipes to write nbt correctly
          -- change all depend researches and craftings
- [x] T0 Generator charge batteries over their max Capacity
- [x] Ionen Collector charge batteries over their max Capacity
- [x] Monocart Charger charge batteries (inside the Monocart) over their max Capacity
- [x] Battery Box charge batteries over their max Capacity (expecting Charge slot)
- [x] Block Breaker don't work: no effekt, delete all items
- [x] Centrifuge randomly replace content of output slots (maybe ==null insted of isEmpty() ?) 
- [x] Plasma Cutter don't consume energy
- [x] Grappling Slime don't consume ernergy
- [x] Tooltip for hologramms in researcher are missing 
- [x] Partpress waste Output from second line if something in the output slot (also with matching item)
- [x] Texture missing in The Research System text
- [x] Many Achivments don't trigger
- [x] Temperature value in machines shows wrong (?° if offline, 0.0° if running) 
- [x] Batterie blocked T0 Generator (investigation needed)
- [x] NeonFurnace smelts everything to nothing

Maybe unfixable:
- Research unlock Command: autocomplete should show "all" and "basic" first

Not reproducable:
- Mainboard data is destroyed, if it is crafted to machine (seen at Optibench)

**Comment by mcenderdragon** [comment] 2017-01-10 15:53
ok cant repdroduce the battery/flash Drive thing, they turn to instand full :/

**Comment by mcenderdragon** [comment] 2017-01-10 17:25
logisitc overlay is working...

**Comment by mcenderdragon** [comment] 2017-01-10 17:56
Damage Bars look this way, and have alway done this.

**Comment by mcenderdragon** [comment] 2017-01-11 17:40
fixed forscher item holograms

**Comment by mcenderdragon** [comment] 2017-01-11 17:58
fixed generator

**Comment by mcenderdragon** [comment] 2017-01-11 17:59
drone station: this is a feature

**Comment by mcenderdragon** [comment] 2017-01-11 18:28
fixed partpress destroy fuel

**Comment by mcenderdragon** [comment] 2017-01-11 18:53
fixed blockbreaker

**Comment by mcenderdragon** [comment] 2017-01-12 12:37
laser, damage bars and optibench should be fixed now

**Comment by mcenderdragon** [comment] 2017-01-17 16:39
yeah I edited your post, please test them again and make a new post so I sew what is new (still not working)

**Comment by mcenderdragon** [comment] 2017-02-05 15:04
- [ ] Falling tree does not render due the FastTESR tests

- optbench should now store its values properly

**Comment by Wugand** [comment] 2017-02-06 01:07
OK, list is up-to-date again

**Comment by mcenderdragon** [comment] 2017-02-06 17:55
mergened 1.10, foxed transport chip,

**Comment by mcenderdragon** [comment] 2017-03-17 23:15
fixed tyros and menelaus light, fastTesr is working, yeah pretty much every other bug should be also fixed.

**Comment by Wugand** [comment] 2017-03-18 21:11
List is up to date again (3 Bugs left)
Currently no other bugs known

**Comment by Wugand** [comment] 2017-03-18 22:28
Ok we found some more bugs ....

The finishing of battery system seems to be my part: @Wugand

**Comment by mcenderdragon** [comment] 2017-03-30 18:59
standart key in now space, research textet are also fixed, fixed ind furnace, and also ind neon furnace, fixed grenades,  fixed partpress, fixed battery overloading, fixed block placer, block breaker was working fine, fixed zentrifuge

**Comment by Wugand** [comment] 2017-03-30 19:53
ok only one missing

**Comment by mcenderdragon** [comment] 2017-04-05 16:22
cant reproduce the optibench bug..., researches is already fixed, fixed partpress,

**Comment by Wugand** [comment] 2017-04-13 20:35
All Bugs fixed!!!

**Closed** 2017-04-13 22:49 UTC
Labels: Bug, Critical, Solved
