### ISSUE TITLE
Potential memory leak while playing Exoria

### ISSUE THREAD

**Issue by Grimjahk** [mcenderdragon/Futurepack-API#458] opened 2018-06-29 01:25 UTC
Playing Exoria now for almost 5 weeks... Open to LAN to play with GF. Machine is on 24/7.

Had to reboot the "server" 3 times over 4.5 weeks for one reason or another (pack-patch was one of them) 

5 days ago I progressed into FP, and started noting some lag spikes, to the point I needed to shut down MC and reboot my machine. every night the server would crash overnight... I suspected there was a memory leak and began watching and tracking it, I'm running on a beefy computer and using 12,288 RAM, but over a few hours the memory would hit 100% allocated which I'd not seen before.

Last night, After I moved ALL of the FP stuff to an unloaded chunk, and rebooted, (specifically not getting in range to load that chunk) there was no memory usage creep, and the server stayed up all night.

I have been attempting to duplicate this on my test machine, but redoing all the research is slow going with limited time to invest.

If there is information I can provide to assist, let me know.

**Comment by mcenderdragon** [comment] 2018-06-29 13:13
use `/fp research @p unlock all` for testing purposes
We are also running a server with FP now for over a month, so far we have not noticed memory issues.

**Comment by Grimjahk** [comment] 2018-06-29 13:20
Thank you for the testing shortcut!

Not a surprise, (about running your own server), I expected it to be thoroughly tested. That's why I mentioned the fact that my experience is in the Exoria pack. There may be a conflict that is triggering it. Also noting that I am not running a dedicated server yet, I'm playing single player and opening to LAN. 

Update, Since my reboot ~36 hours ago, (and not loading the FP chunk) my RAM Allocation has not passed 40%.

**Comment by mcenderdragon** [comment] 2018-06-29 20:32
LAN is different from a dedicated server as there are other function used for netty. If you are noticing a memory leak you can use visualVM to make a memory dump a check what is taking lots of memorie.

**Comment by mcenderdragon** [comment] 2018-07-02 10:56
Also what machines/blocks are in these chunks ?

**Comment by mcenderdragon** [comment] 2019-06-01 11:44
I dont know if this was also caused by this but I found some kind of memory leak #570.
But the tickspeed suffered in out test way earlier then the RAM (then again our server has 16 cores but each core is only on ~4GHz)

I will close this, feel free to reopen if this happens again.

**Closed as completed by mcenderdragon** 2019-06-01 11:44 UTC
Labels: Investigation-needed
