### ISSUE TITLE
1.18 composite fishing rod not working

### ISSUE THREAD

**Issue by geddon7** [mcenderdragon/Futurepack-API#913] opened 2022-07-04 21:19 UTC
**Describe the bug**
the composite fishing rod seems to instantly call back the end point

**To Reproduce**
try to use the rod

**Additional context**
I am using 18 total mods including:
appleskin
block ui
clumps
curio of undying
curios
omum_ornamentum
jet
journey map
mantle mineclonies
multipiston
optifine
structurize
tinkers construct
the one probe
travelers backpack

**Version**
Minecraft Version: 1.18.2
Forge Version: 1.18.2-40.1.52
Futurepack Version: 1.18.0.7403

**Logs**
I have a copy of the world save, don't know how to give it to you and the end lure thing is called back too quickly to get a screenshot

**Comment by Yirok42** [comment] 2022-07-05 03:10
This is a duplicate of #850
The resolution of Forge defect 8424 is needed.

**Comment by mcenderdragon** [comment] 2022-07-05 12:02
thanks @Yirok42

**Closed as completed by mcenderdragon** 2022-07-05 12:02 UTC
Labels: Bug, invalid/duplicated, Investigation-needed
