### ISSUE TITLE
Scanner crashes server

### ISSUE THREAD

**Issue by TheRealM18** [mcenderdragon/Futurepack-API#545] opened 2019-02-11 14:34 UTC
Using Futurepack with the scanner and researching the metal block, you if you click on the metallurgy, you crash the minecraft jar, thus you crash the inter world with you. this was found one the Epic Crafting: Origins pack, and originally tried with my mod, then yours, and the outcome was the same.  There is not crash report, but I will upload all logs.
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/2851460/latest.log)
[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/2851461/FP-Latest.log)

debug log in teamspeak 3.

**Comment by TheRealM18** [comment] 2019-02-11 15:30
cause by me, fixed in lastest

**Comment by mcenderdragon** [comment] 2019-02-11 16:22
which item was in the scanner when this happened?

**Comment by mcenderdragon** [comment] 2019-02-11 17:31
Also this was most likely caused by a custom Research by your addons. This is fixed in [26.4.43](https://redsnake-games.de/Downloads/fp/fp.php?t=T2BQvQOHA6uGr353cIblNg--)

**Comment by mcenderdragon** [comment] 2019-02-11 22:41
Also this was most likely caused by a custom Research by your addons. This is fixed in [26.4.43](https://redsnake-games.de/Downloads/fp/fp.php?t=T2BQvQOHA6uGr353cIblNg--)

**Closed as completed** 2019-03-10 20:36 UTC
Labels: Bug, Critical, Solved in Dev
