### ISSUE TITLE
1.12 crash

### ISSUE THREAD

**Issue by MadRatSRP** [mcenderdragon/Futurepack-API#318] opened 2017-11-25 12:27 UTC
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.minecraft.world.World.func_175644_a(World.java:3015)
	at futurepack.common.FPMain.onWorldTick(FPMain.java:542)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_449_FPMain_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by MadRatSRP** [comment] 2017-11-25 13:03
![modlist](https://user-images.githubusercontent.com/29717217/33230729-1dc61fa6-d1fa-11e7-9d2e-21780b374b1a.png)
here is my modlist

**Comment by mcenderdragon** [comment] 2017-11-25 13:10
Ok the only thing I can say is: this crash was caused by some other mod modifing the entity list from another thread. but thats it. I also I think I c ant fix this on my side because this could happen any time soon again .

**Comment by mcenderdragon** [comment] 2017-11-25 13:38
This should be fixed: [26.3.8](http://redsnake-games.de/Downloads/fp/fp.php?version=26.3.8)

**Comment by MadRatSRP** [comment] 2017-11-25 13:52
Thanks, its working now. Probably it happened cause of FoamFix option of deduplicateModelsMaxRecursion changed to 9.

**Comment by mcenderdragon** [comment] 2017-11-25 15:26
yeah you should check the log, it now dont kill the game if it crashes but it sill does crash, so notice me if it spams the log with crashes or only sometimes.

**Closed as completed** 2017-12-21 12:48 UTC
Labels: Bug, Critical, Solved in Dev
