### ISSUE TITLE
Bug tech tree

### ISSUE THREAD

**Issue by Husdif** [mcenderdragon/Futurepack-API#795] opened 2021-05-07 11:36 UTC
Lost all research
When I open the tech tree, I have lost all the research which I have done the last days. The tech tree is bug and I can't do anything. The tech tree it's just an icon of "story". Except this icon, all the tech tree is invisible but they are present like you can see on the last Pic. 
It's the 1.16.4-31.1.8226version of the mod Future pack. 

![16203870887968208728444480142921](https://user-images.githubusercontent.com/83818747/117443543-905d6000-af38-11eb-8b57-a35c6e931e19.jpg)
![16203871096081755870526013877051](https://user-images.githubusercontent.com/83818747/117443572-9eab7c00-af38-11eb-8e10-6e591b229c3f.jpg)
![16203943029786610002700190911096](https://user-images.githubusercontent.com/83818747/117457271-5b0d3e00-af49-11eb-92b9-9bf2c9ae9771.jpg)

**Comment by Yirok42** [comment] 2021-05-20 02:33
Sounds like a duplicate of #784

**Comment by mcenderdragon** [comment] 2021-05-31 11:07
Duplicate of #784 , please test the version linked there.

**Closed as completed by mcenderdragon** 2021-05-31 11:07 UTC
Labels: Bug, invalid/duplicated, Investigation-needed
