### ISSUE TITLE
Minecraft 1-12-2 forge 2836 and fp 26-4-80 Exception in thread "futurepack.api.resources.AssetsDownloader@4104698e"  Process exited with code 0

### ISSUE THREAD

**Issue by trogarus** [mcenderdragon/Futurepack-API#572] opened 2019-05-31 18:27 UTC
Sorry, seems some things here at git have changed and I didn't intend to link this to #572.

After updating, I get that error and the server shuts down. No crash log.
[latest.log](https://github.com/mcenderdragon/Futurepack-API/files/3242460/latest.log)

[FP-Latest.log](https://github.com/mcenderdragon/Futurepack-API/files/3242463/FP-Latest.log)

***EDIT***
Nice to see you're still developing this.

**Comment by trogarus** [comment] 2019-05-31 19:31
Upon further investigation, it seems to be some kind of interaction between FP and hatchery latest.

Looking at the mods I updated in the pack, rolling back FP didn't fix the issue. Rolling back hatchery did.

Hatchery version in question hatchery 1.12.2-2.2.2

**Comment by mcenderdragon** [comment] 2019-05-31 22:04
I think the main cause is this 
`[14:14:29] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: trogarus lost connection: Timed out`

you get somehow a timeout while joining the world.

**Comment by trogarus** [comment] 2019-05-31 23:37
I do, but it is not a network connection. After rolling hatchery back it stopped shutting down my local server. I’ve not timed out since

**Comment by mcenderdragon** [comment] 2019-06-01 00:34
weird, I guess you should report that to hatchery too.

**Comment by trogarus** [comment] 2019-06-01 03:13
Still investigating. Going mod by mod in the update yesterday. Will report back. Making sure there are no other updated mods involved. Things were OK before I updated them.

**Comment by trogarus** [comment] 2019-06-01 18:30
Seems to be pointing to backpacks mod at this point. Have been running game a bit as I roll back and reset one mod at a time. Life is making the process slow 😁

**Comment by mcenderdragon** [comment] 2019-06-01 18:57
take your time, please report back if you find the cause of this.

**Comment by trogarus** [comment] 2019-06-07 22:10
Making it official. I've ran the game a while now with the Backpacks rolled back and seems no issues now.

backpacks+1.12.2+-+3.5.6.jar is the issue that seemed to be somehow causing the issue. Maybe some kind of weird mod interaction between the two? Don't know, but it seems rolling that mod back to previous version fixed things. Sorry to take so long to report back. If I run into anything related to this again, I'll post back, but seems, I'm probably not going to given the issue seems resolved.

**Comment by mcenderdragon** [comment] 2019-06-08 09:27
Cool :) I will close this so feel free to reopen when it happens again.

**Closed as completed by mcenderdragon** 2019-06-08 09:27 UTC
Labels: Investigation-needed
