### ISSUE TITLE
missing story.nav.mincra

### ISSUE THREAD

**Issue by pietru2004** [mcenderdragon/Futurepack-API#943] opened 2022-11-13 18:52 UTC
**Screenshots**
![obraz](https://user-images.githubusercontent.com/51274570/201538957-f0f7c46a-70cd-4b60-b537-8ae06be35dd7.png)

**Additional context**
Would it be possible to get that story point to read Temporary on github ?

**Version**
Minecraft Version: 1.18.2
Futurepack Version: Futurepack-1.18.2-33.0.7482

**Comment by mcenderdragon** [comment] 2022-11-13 19:00
hte story is nto wiritten yet and I dont know what @Wugand has planned for it.

**Comment by Yirok42** [comment] 2022-12-28 04:06
Duplicate of #888

**Comment by Wugand** [comment] 2023-03-07 19:38
Thank you for the report. Some features are not fully finished yet, so there are missing description. We try to complete that as sson as possible.
Your Issue was added to the collection thread. #962

**Closed as not planned by Wugand** 2023-03-07 19:38 UTC
Labels: Bug, Feature, 1.18.x
