### ISSUE TITLE
Hologramm don't work for Cables

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#25] opened 2016-10-07 18:22 UTC
Setting a hologramm for an calbe does no effect. Pipes work correctly.

**Comment by mcenderdragon** [comment] 2016-10-07 21:17
no

**Comment by mcenderdragon** [comment] 2016-10-07 21:21
Duplicate of this: https://github.com/mcenderdragon/Futurepack-API/issues/19

**Comment by mcenderdragon** [comment] 2016-10-07 21:21
Also tested in single or in mutliplayer?

**Closed** 2016-10-20 20:29 UTC
Labels: invalid, Solved
