### ISSUE TITLE
Server crashing continuously after middle clicking a sapling planter

### ISSUE THREAD

**Issue by copygirl** [mcenderdragon/Futurepack-API#296] opened 2017-11-02 09:37 UTC
**Crash report:** [crash-2017-11-02_05.04.18-server.txt](https://gist.github.com/copygirl/3c51f10a1fc8bdb5d47a1ae1916c1cac)

This happened to me on the BTM Moon server. Thus, we can't use it at the moment, and might be high priority for us to be able to continue preparations. Though perhaps another server admin can fix the issue using MCEdit, or restoring a backup, neither of which I personally know how to do.

(Poking @modmuss50, too.)

**Comment by Wugand** [comment] 2017-11-02 14:34
Hotfix provided to BTM: "Futurepack-26.2.27-hotfix2.jar"

The crash is caused by calling insertItem with an null ItemStack. Maybe by an Themal dynamics ItemDuct
Maybe other machines are in danger!

**Comment by Wugand** [comment] 2017-11-02 14:47
Note: The middle clicks seems to don't have an relation to the crash

**Comment by KingLemming** [comment] 2017-11-02 14:57
ItemDucts absolutely did not cause this, so we are clear. And I *really* dislike the panicked blame shifting.

**Comment by Wugand** [comment] 2017-11-02 15:04
@KingLemming
Sorry for that. We added null checks our self. And see no reseaon, so we asked the next mod appearing in the log.
If you don't pass null, ok. Thanks for the information. We search at other places, which can cause the probelm.
(Maybe I should mark such issues as questions next time)

We definitly don't want to blame, we simple search for the reason.

**Comment by Wugand** [comment] 2017-11-02 15:55
Ok, for some reason another vaiable get null. Maybe a coremod or somthing. fixed now.

**Closed as completed by Wugand** 2017-11-02 15:55 UTC
Labels: Bug, Critical, Solved in Dev, Other Mod's fault/ Mod interaction
