### ISSUE TITLE
Network Deadlock (and watchdog crash)

### ISSUE THREAD

**Issue by belathus** [mcenderdragon/Futurepack-API#911] opened 2022-06-27 00:28 UTC
**Describe the bug**
I'm trying to research plasma lamps, one of the last few research items I have available to me (I gave myself the prerequisite Menelaus research; I think we're still playing on a version that doesn't yet have Menelaus.) I recently made a couple of torus cores that have over 100 core power and tossed them in a calculation module with an appropriate amount of RAM; total core power is 203 and total used core power is something like 175. Anyway, tried to reproduce the problem in single-player and, well, it is now hung before I even got a chance to set up a researcher. I did, however, set up a super crusher and neon furnace with those 100 core power torus cores and 30 ram power torus ram (spawned them in) and set them in a loop to generate support and the server hung shortly after I gave them power (using five ion collectors with the same cores), so I am guessing it isn't just the calculation module.

I should point out that I've managed to get core power that high in survival, so this isn't simply a matter of using a command to create a core with excessive amounts of core power. It did, however, take a decent amount of effort to get that high.

**To Reproduce**
1. spawn in cores and ram with way too much power.
2. Insert them into machines.
3. Let those machines run.
4. Server hangs.

**Screenshots**
![ram.png](https://cdn.discordapp.com/attachments/176845387431149568/990742394397917184/ram.png)

**Additional context**

**Version**
Minecraft Version: 1.18.2
Forge Version: 40.1.30
Futurepack Version: 40.1.30

**Logs**
https://gist.github.com/belathus/b1cd2fb6e802aa418b689eef71286b8d

**Comment by belathus** [comment] 2022-06-27 06:51
So, uh, maybe it was that network antenna thing? but that doesn't really explain the freeze in single player. Not sure what happened there.

**Comment by mcenderdragon** [comment] 2022-06-27 17:56
ok so the network thread (ingame network thing) waited on the server thread (to get a block or something) and the server thread waited on the nerwork thread, and so the threads waite don each other and the game stopped...

**Comment by mcenderdragon** [comment] 2022-06-29 16:35
this is most likely fixed in [33.0.7409](http://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.18.2-33.0.7409/futurepack-1.18.2-33.0.7409.jar) (please check if it actually works since you seems to be able to reproduce this regularly)

**Comment by belathus** [comment] 2022-06-29 19:31
Will do.

**Closed as completed** 2022-07-01 17:59 UTC
Labels: Bug, Critical, Solved in Dev, 1.18.x
