### ISSUE TITLE
Connecting a neon furnace and industrial neon furnace with support pipes causes a server crash

### ISSUE THREAD

**Issue by glarmer** [mcenderdragon/Futurepack-API#780] opened 2021-03-26 05:03 UTC
VERSION futurepack 31.1.8176, 1.16.5

Hi, I asked the player who was facing the issue to describe the issue in full detail and he told me "when you connect a neon furnace and industrial neon furnace on mp with support pipes, it just crashes the server. both machines have support chips + fast enough core/ram.", he tried doing it in single player and couldn't replicate the crash. Switching to support cables worked and allowed him to progress.

The exception thrown is as follows:
https://pastebin.com/U1LCttLr

**Comment by glarmer** [comment] 2021-03-27 20:46
Forge version is 36.1.0, sorry forgot to mention :)

**Comment by mcenderdragon** [comment] 2021-03-29 17:10
is this crash reprdocueable ? (I real realy want to belive that this was a one off weirdness becuase if not then shit hit the fan)

**Comment by glarmer** [comment] 2021-03-30 12:22
The player was able to do it after restarting the server

**Comment by Wugand** [comment] 2021-04-07 19:11
Can you please make a video or screenshots how you build it / how it happens. We were currently not able to reproduce it.

**Comment by mcenderdragon** [comment] 2021-07-14 10:37
I added more debug output to this crash can you try to reproduce it with this version: [Futurepack 31.2.6856](http://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.16.4-31.2.6856/futurepack-1.16.4-31.2.6856.jar)

**Comment by FaeAura** [comment] 2021-09-16 19:52
This bug is reproducable, I've encountered it myself. the instant I connected support cables from my neon furnace to my industrial neon furnace, the server just went poof and I'm having to fix yet another ticking block/tile entity crash loop thanks to this mod. 
I like this mod a lot but this is annoying and ridiculous. please fix your shit, guys x.x

**Comment by mcenderdragon** [comment] 2021-09-16 19:53
> 
> 
> This bug is reproducable, I've encountered it myself. the instant I connected support cables from my neon furnace to my industrial neon furnace, the server just went poof and I'm having to fix yet another ticking block/tile entity crash loop thanks to this mod.
> I like this mod a lot but this is annoying and ridiculous. please fix your shit, guys x.x

no crash report no fix. I can't reproduce this and I cant see the future, so there is nothing I can do.

**Comment by FaeAura** [comment] 2021-09-16 19:55
right, hold on, I'm rather new to adding crash logs to github posts without flat out copy pasting it in. this should work though, right? I'm trying to attach it.
[crash-2021-09-16_19.41.17-server.txt](https://github.com/mcenderdragon/Futurepack-API/files/7180613/crash-2021-09-16_19.41.17-server.txt)

**Comment by mcenderdragon** [comment] 2021-09-16 20:10
try this version: http://redsnake-games.de/maven/redsnakegames/mcenderdragon/futurepack/1.16.5-31.3.6978/futurepack-1.16.5-31.3.6978.jar (if it doesnt work then the build is still ongoing, try in ~5 minutes again)

**Comment by FaeAura** [comment] 2021-09-16 20:26
okay so that fixes it. I think this issue should be closed with "update the mod"

**Comment by mcenderdragon** [comment] 2021-09-16 20:27
that fix was only for mroe error message since OP error is unique, but since they never answered back I will clsoe this. they jsut need to open ti again.

**Comment by FaeAura** [comment] 2021-09-16 20:30
hold on, one sec. by the way your link to the 6978 version doesn't work. so I updated to 6976 and the issue still persists when you make the support cable line too long apparently.

**Comment by mcenderdragon** [comment] 2021-09-16 20:31
for me the link works for 6978

**Comment by FaeAura** [comment] 2021-09-16 20:33
okay let me try this thing again with that version of the mod. if this setup works then there we go, if not let me describe just how it went down:
Placed down Neon Furnace, added the TLC? TLT? TLS? the second red one that uses retinum anyway - core. added the support chip, made a support cable line of maybe six or so cables. bam. server down.

**Comment by mcenderdragon** [comment] 2021-09-16 20:34
adn of course 6976 doesnt work the fix was just made by me lol.

**Comment by FaeAura** [comment] 2021-09-16 21:02
yep fixed now for sure.

**Closed as completed** 2021-11-24 14:08 UTC
Labels: Bug, Solved in Dev, 1.16.x
