### ISSUE TITLE
[Futurepack-1.12.2-26.3.417] Crash with RemoveQuee

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#502] opened 2018-10-11 14:49 UTC
https://hastebin.com/coqanicufe.pl

**Comment by mcenderdragon** [comment] 2018-10-11 16:02
as it turns out it the ArrayList#add, crashed because in the array öis t the array was null. As this should be impossiblle I will close this issue. (Also I can nothing do about it , java itself crashes.)

**Comment by mcenderdragon** [comment] 2018-10-23 11:02
```
java.lang.NullPointerException: Ticking block entity
	at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
	at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
	at java.util.ArrayList.add(Unknown Source)
	at futurepack.common.FPSelectorHelper$RemoveQuee.addRemoveAll(FPSelectorHelper.java:428)
	at futurepack.common.FPSelectorHelper.removeIfPossible(FPSelectorHelper.java:220)
	at futurepack.common.FPSelectorHelper.func_184376_a(FPSelectorHelper.java:241)
	at net.minecraft.world.World.func_184138_a(World.java:431)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:375)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at net.minecraft.world.World.func_175656_a(World.java:424)
	at futurepack.common.block.TileEntityWasserTurbine.updateTile(TileEntityWasserTurbine.java:42)
	at futurepack.common.block.TileEntityModificationBase.doUpdate(TileEntityModificationBase.java:352)
	at futurepack.common.block.TileEntityModificationBase.func_73660_a(TileEntityModificationBase.java:198)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by mcenderdragon** [comment] 2018-10-23 11:04
I think this is caused by multithreading as #506 has similar code. Maybe some blocks of memory are not avilable yte and it crashes. Or the JVM optimised the syncronised away...

**Comment by mcenderdragon** [comment] 2018-10-23 11:18
[Version 26.3.450](https://redsnake-games.de/Downloads/fp/fp.php?t=V_jHO4G_MHiQQWr3VdP9_Q--)

**Closed as completed** 2018-11-17 15:05 UTC
Labels: Bug, Critical, Solved in Dev
