### ISSUE TITLE
crash on closing "strange document" item

### ISSUE THREAD

**Issue by Cat-McCatface** [mcenderdragon/Futurepack-API#1] opened 2016-09-03 03:25 UTC
opening and closing the item multiple times in quick succession causes a crash. hopefully not caused by an older version of forge.

crash log: http://pastebin.com/3Qvavi6p
Futurepack-1.10.2-24.1.1
forge: 2052

**Comment by mcenderdragon** [comment] 2016-09-03 08:57
Does this also happen if you only use the Futurepack and no other Mods? (There are some coremods and this will sort out they make these problems. ) 

Edit:
In Forge 2014 I am not able to reproduce this bug. Could you try this forge version?

**Comment by Cat-McCatface** [comment] 2016-09-04 04:32
Updated to forge 2073 (same as sponge server component of the modpack) and made new world and got a different error
Time: 9/3/16 11:21 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:535)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:535)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: futurepack.common.gui.GuiNotiz

Updated to latest public forge for 1.10.2 (2076) and I can't reproduce it anymore with same mods installed. Guess it is old version problems X)
I don't know what change other than 2074's rendering fix did it but I'll take it. I got a duplicate document item on entering the test world but that's small stuff.

**Comment by mcenderdragon** [comment] 2016-09-04 10:51
This is strange, but it seems like a forge bug, and as the latest Forge version works, I will close this :)

**Closed by mcenderdragon** 2016-09-04 10:51 UTC
Labels: Critical
