### ISSUE TITLE
[1.14] Research requiring Research Module - Energy do not work

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#613] opened 2020-01-03 22:24 UTC
Version: 28.0.8
Forge: 28.1.109

Even when the Researcher has a Research Module - Energy which is filled with NE next to it, the energy research bar does not fill up.
;
Adding a Network Cable does not help either.

**Comment by mcenderdragon** [comment] 2020-01-11 14:18
Turns out TileEntites can only be accessed from the main thread...

**Comment by mcenderdragon** [comment] 2020-01-17 17:35
https://www.patreon.com/posts/33229425

**Comment by qrss** [comment] 2020-01-17 19:38
Are you sure this is fixed in Futurepack 28.0.10?

It is still not working for me.

Forge 28.1.115

![researcher2](https://user-images.githubusercontent.com/32312262/72641510-108e3980-3973-11ea-9dca-2f775ad0b1d6.gif)

**Comment by mcenderdragon** [comment] 2020-01-17 22:10
hmmm, I will check that.

**Comment by qrss** [comment] 2020-01-17 22:36
Interesting, I loaded the world again, and the research bar started filling.

Sorry, it might have been a false alarm, perhaps having to do with me starting the world and placing the researcher in the last version.

**Comment by qrss** [comment] 2020-01-17 22:42
No, there is still something glitchy. The Assembly table research finished, but when I put in the next research, the energy bar is again not filling.

**Comment by qrss** [comment] 2020-01-17 22:49
Ok, this is quite weird.

If I leave the required materials in the researcher, do Save and Quit and load the world again, then the bar does not start filling.

However, if I close Minecraft completely, start it up again and load the world, then the bar starts filling.

Whenever I want to research a new thing, I need to close Minecraft completely and load the world again, in order to get the Energy bar to start filling up.

**Comment by mcenderdragon** [comment] 2020-01-17 23:03
this is weird...

**Comment by qrss** [comment] 2020-01-17 23:49
One thing that is different between closing Minecraft completely and just doing Save and Quit before loading the world again is the lagspike that you get first time opening the GUI of a Futurepack device.

I guess it has to load some things. Perhaps there is some process that is nescessary for the energy research bar to fill, that starts up along with the lagspike.

Perhaps, it only gets the correct inputs during the loading process (lagspike)?

Or perhaps it terminates for some reason if it does not find something to do?

DISCLAIMER: I have no idea how Minecraft or Futurepack work.

**Comment by mcenderdragon** [comment] 2020-01-18 11:31
This should not have wokred in the first place: all TileEntities accesses need to be done from teh main thread and guess who overlooked another 2 of them causeing it to sometimes work & sometimes not ^^

**Comment by mcenderdragon** [comment] 2020-01-18 12:46
Should be fixed: https://www.mediafire.com/file/hvm6w77c33ohxg4/Futurepack-1.14.4-28.0.11.jar/file

**Comment by qrss** [comment] 2020-01-18 13:06
Hmm, I was checking whether this works, opening and closing the GUI's of the Energy Research Module and the Researcher, and now my TPS is literally permanently zero.

**Comment by mcenderdragon** [comment] 2020-01-18 13:13
could you use VisualVM and use teh Sampler so i can get an Idea of what is taking so long?

**Comment by qrss** [comment] 2020-01-18 13:26
Well, I haven't used these tools before, but I can try.

I guess by Sampler you mean this:
https://www.curseforge.com/minecraft/mc-mods/sampler
which does not seem to be available for 1.14,
and by VisualVM mean this:
https://visualvm.github.io/index.html
which I'll try to use instead.

**Comment by mcenderdragon** [comment] 2020-01-18 13:33
Sampler is an option is VisualVM, you can also try to use the command `/debug start` wait atleast 60 seconds `/debug stop` follower by a `/debug report`. Inside the debug folder inside the miencraft folder should now be a zip and a profiler results.txt

**Comment by qrss** [comment] 2020-01-18 15:19
The debug command did not create any debug folder.

I'm not sure what I'm looking for in the VisualVM sampler, but here is a thread dump and a snapshot from that zero TPS state. No chunks are loading and doing Save & Exit will just stay on the saving screen forever.

[thread_dump.txt](https://github.com/mcenderdragon/Futurepack-API/files/4080851/thread_dump.txt)

[snapshot.zip](https://github.com/mcenderdragon/Futurepack-API/files/4080852/snapshot.zip)

**Comment by mcenderdragon** [comment] 2020-01-18 15:26
Everything somehow locks on the server to get the tileEntity, while the server is not doing anything... or rather waiting on itself...

**Comment by mcenderdragon** [comment] 2020-01-18 15:42
What do you use for researching? how many machines and such?

**Comment by qrss** [comment] 2020-01-18 16:25
I just have a Researcher and an Energy Module.

Perhaps it has something to do with my computer not being very fast, but I can quite reliably reproduce this by right clicking on the Energy Module and the Researcher while the following world is loading:

https://drive.google.com/open?id=1TXS2B2mnf40f1w_E5umacQ3XsWOUZnVb

This does not happen always, and perhaps requires the initial lagspike you get when opening a futurepack device for the first time?

**Comment by qrss** [comment] 2020-01-18 16:44
If you can't reproduce this, then its fine. Hopefully nobody else can either.

**Comment by mcenderdragon** [comment] 2020-01-18 16:58
I could not reproduce them, but I also amde small changes. Please test if it works better: https://www.mediafire.com/file/zd2j1apym9isd4y/Futurepack-1.14.4-28.0.12.jar/file

**Comment by qrss** [comment] 2020-01-18 17:38
I tested the reproduction sequence 6 times and the issue did not appear.

Either you fixed it (good job!) or I've just been lucky to not hit the issue (let us hope not).

**Closed as completed** 2020-01-18 19:38 UTC
Labels: Bug, Solved in Dev, 1.14.x

**Comment by rynarok** [comment] 2022-10-11 03:25
Hi there I have opened a new bug report, but id might as well put it here. Having the exact same issue, except in 1.18.

Futurepack-1.18.2-33.0.7441

**Comment by Peekofwar** [comment] 2022-10-16 22:23
Same... I'm having this issue on a survival server. 

Okay, I put dirt in the slot and it stopped complaining...? Why does it say no energy until I put something in the slot that requires it??

So it seems (for me at least) that if you put the item in the slot, it will switch from saying "no energy" to working. It should have a different message or have a blue outline if there is energy available with no item processing.
