### ISSUE TITLE
The Stöpsel causing the client to hang on ship teleport

### ISSUE THREAD

**Issue by qrss** [mcenderdragon/Futurepack-API#526] opened 2018-12-11 23:47 UTC
Version: 26.3.461

After adding a Stöpsel to some machinery on my ship, the client started to quite often hang on ship teleport (within a dimension). The hang seems to happen after the teleport. After restarting the client, I can connect to the server again, and everything seems fine. I'm guessing this does nothing to the server.

The can even happen when the Stöpsel is just sitting between empty Wardrobes. When the Stöpsel block is removed from the ship, the teleporting works without issues.

Since the client hangs, but does not crash, the logs don't contain anything informative, unless I'm not looking at the right logs.

**Comment by mcenderdragon** [comment] 2018-12-16 17:08
so like a frame takes way longer then it should nomaly do?

**Comment by qrss** [comment] 2018-12-16 17:18
No, the client complely stops responding and needs to be closed.

**Comment by mcenderdragon** [comment] 2018-12-16 17:19
It completly stops and does not work again even after a few secinds/minuits?

**Comment by qrss** [comment] 2018-12-16 17:24
Well, I did not wait more than 5 minutes, but I can test for longer.

**Comment by mcenderdragon** [comment] 2018-12-16 17:34
no 5 minuts is enough. It did crash but somewhere silently :/ does the debug.log and the FP latest log show any hints ?

**Comment by qrss** [comment] 2018-12-16 17:54
Not really.

The end of debug.log just contains 

[19:29:56] [Client thread/INFO] [Futurepack]: Send Research Request to Server
[19:29:56] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] chat.spaceship.GO
[19:29:56] [Netty Client IO #1/INFO] [Futurepack]: Get Research Data from Server

again and again, while the end of FP-Latest.log contains 

[19:29:56][Client thread] Send Research Request to Server
[19:29:56][Netty Client IO #1] Get Research Data from Server

again and again

**Comment by mcenderdragon** [comment] 2018-12-16 18:20
even while the client hangs ?

**Comment by qrss** [comment] 2018-12-16 18:45
The logs contain that after the client is closed after is stops responding.

**Comment by mcenderdragon** [comment] 2018-12-16 19:26
that is strange...

**Comment by mcenderdragon** [comment] 2018-12-16 19:36
I was not able to reproduce this in single player in debug. Maybe a server issue.

**Comment by qrss** [comment] 2018-12-16 19:40
Well, you can get on the server with me with debug and see if it happens to both of us when I teleport, or just me.

**Comment by mcenderdragon** [comment] 2018-12-16 19:42
I did not happen to my client at the same version as on the server in singleplayer. Lets test it on out server.

**Comment by mcenderdragon** [comment] 2018-12-16 19:45
You just disappered/got a timeout and nothing happened to me. We are still in the overworld and nothing got tiggered server side it seems.

**Comment by mcenderdragon** [comment] 2018-12-16 19:49
The crash does happen on in world teleportation.

**Comment by mcenderdragon** [comment] 2018-12-16 19:58
I did the in world teleport and it still happened to you, di yiu have OPtifine or any other mods installed ?

**Comment by mcenderdragon** [comment] 2018-12-16 20:16
![client ruckler](https://user-images.githubusercontent.com/6342933/50058388-d18e2300-0177-11e9-8047-64281766e260.JPG)

I could reproduce it in mutliplayer. This is where the client currently is.

**Comment by mcenderdragon** [comment] 2018-12-16 20:22
![client ruckler 2](https://user-images.githubusercontent.com/6342933/50058438-9a6c4180-0178-11e9-9f73-d5488f794d24.JPG)
 func_152343_a => addScheduledTask
 func_147585_a => markBlockRangeForRenderUpdate

**Comment by mcenderdragon** [comment] 2018-12-16 20:27
OK yeag basicly the client dead locks itself while waiting for Thread sync events. THese crashes should be very unlikly but apprently there are cases where you can reproduce them.

**Comment by qrss** [comment] 2018-12-16 20:35
It is weird though that the Stöpsel is somehow causing this. It has never happened without that block on the ship. It must be doing something differently than other blocks.

**Comment by mcenderdragon** [comment] 2018-12-17 20:42
It is mainly a timing and amount error, I guess if you have more intependend pipe / wire systems the same crash could happen.

**Comment by mcenderdragon** [comment] 2018-12-17 21:32
This should be fixed in 26.3.473. But sideeffects may occur; time will tell ^^

**Closed as completed** 2018-12-25 00:01 UTC
Labels: Bug, Critical, Solved in Dev, Multiplayer
