### ISSUE TITLE
Crash with Morpheus 1.11.2

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#209] opened 2017-07-08 21:49 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.13.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 08.07.17 22:47
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Morpheus (morpheus)
Caused by: java.lang.NoClassDefFoundError: net/quetzi/morpheus/api/INewDayHandler
	at net.quetzi.morpheus.Morpheus.<clinit>(Morpheus.java:34)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:546)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:582)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.quetzi.morpheus.api.INewDayHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 31 more
Caused by: java.lang.SecurityException: class "net.quetzi.morpheus.api.INewDayHandler"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3816911920 bytes (3640 MB) / 4116185088 bytes (3925 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms4g -Xmx6g
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2265 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2265-universal.jar) 
	UC	forge{13.20.0.2265} [Minecraft Forge] (forge-1.11.2-13.20.0.2265-universal.jar) 
	UC	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.0.1.jar) 
	UC	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UC	chisel{MC1.11.2-0.0.9.13} [Chisel] (Chisel-MC1.11.2-0.0.9.13.jar) 
	UC	forestry{5.3.2.67} [Forestry] (forestry_1.11.2-5.3.2.67.jar) 
	UC	fp{25.2.104} [Futurepack] (Futurepack-1.11.2-25.2.104.jar) 
	UC	fp.api{1.1.0} [Futurepack API] (Futurepack-1.11.2-25.2.104.jar) 
	UC	hammercore{1.4.9} [Hammer Core] (HammerCore_1.11.2-1.4.9.jar) 
	UC	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UC	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UC	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UC	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UE	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UC	solarfluxreborn{2.15r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.15r.jar) 
	UC	storagedrawers{1.11.2-4.2.1} [Storage Drawers] (StorageDrawers-1.11.2-4.2.1.jar) 
	UC	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.13.jar)
  team.chisel.common.asm.ChiselTransformer
SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by mcenderdragon** [comment] 2017-07-08 21:59
Caused by: java.lang.SecurityException: class "net.quetzi.morpheus.api.INewDayHandler"'s signer information does not match signer information of other classes in the same package

**Comment by mcenderdragon** [comment] 2017-07-09 12:45
Should be fixed

**Comment by mcenderdragon** [comment] 2017-07-20 09:55
[This version](http://redsnake-games.de/Downloads/fp/fp.php?version=25.2.116) should fix it, hopefully

**Comment by Wugand** [comment] 2017-07-20 18:30
Tested, it seems it works!

**Closed as completed** 2017-07-22 01:37 UTC
Labels: Bug, Critical, Solved in Dev

**Comment by drewbit** [comment] 2017-07-29 08:41
Sorry to reopen on you, but looks like this exact same issue is happening again in 1.12 with:

Futurepack Version: Futurepack-1.12-26.1.2
Morpheus Version:  Morpheus-1.12-3.3.2

Removing Futurepack fixes the issue. 
Here's the log just in case: https://pastebin.com/Bxq0aAbz
