### ISSUE TITLE
Spawner Chest

### ISSUE THREAD

**Issue by Cat940** [mcenderdragon/Futurepack-API#704] opened 2020-10-09 17:33 UTC
Hello. I can't place spawners afterpicking them up with spawner chest. Can You please help me, or fix this if it's a bug?
Some information :
minexraf version 1.15.2
futurepack version 20.1.0

**Comment by mcenderdragon** [comment] 2020-10-09 21:18
Duplicate of #694

**Closed as completed by mcenderdragon** 2020-10-09 21:18 UTC
